import path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import inquirer from 'inquirer';
import { runScannerAgent } from '../scanner/scanner.agent.js';
import { runEvidenceCollector } from '../collector/collector.agent.js';
import { runPlannerAgent } from '../planner/planner.agent.js';
import { runCodegenAgent } from '../codegen/codegen.agent.js';
import { validatePatches, displayDiff } from '../../patch/validator.js';
import { commitPatches } from '../../patch/apply.js';
import { recordFixHistory, initDb } from '../../memory/sqlite/sqliteDb.js';
import { ProjectContext } from '../../scanner/projectScanner.js';
import { FilePatch } from '../../patch/patchEngine.js';

export interface WorkflowState {
  projectRoot: string;
  issue: string;
  autoApply: boolean;
  context?: ProjectContext;
  retrievedFiles?: string[];
  diagnosis?: {
    explanation: string;
    proposedAction: string;
    relevantFiles: { filePath: string; reason: string; confidence: number }[];
  };
  bugFix?: {
    explanation: string;
    patches: FilePatch[];
    rawLLMResponse: string;
  };
  errors: string[];
}

export async function executeFixWorkflow(
  projectRoot: string,
  issue: string,
  autoApply: boolean
): Promise<WorkflowState> {
  const root = path.resolve(projectRoot);
  
  // Initialize DB before starting
  await initDb(root);

  const state: WorkflowState = {
    projectRoot: root,
    issue,
    autoApply,
    errors: [],
  };

  // 1. Scanner Node
  const scanSpinner = ora(chalk.blue('Scanner Node: Scanning directory structure...')).start();
  try {
    state.context = await runScannerAgent(root);
    scanSpinner.succeed(chalk.green('Scanner Node: Scanning complete.'));
  } catch (err: any) {
    scanSpinner.fail(chalk.red(`Scanner Node failed: ${err.message}`));
    state.errors.push(err.message);
    return state;
  }

  // 2. Evidence Collector Node
  const collectSpinner = ora(chalk.blue('Evidence Collector Node: Gathering codebase variables...')).start();
  let evidence;
  try {
    evidence = await runEvidenceCollector(root, state.context, issue);
    state.retrievedFiles = evidence.targetFiles;
    collectSpinner.succeed(chalk.green(`Evidence Collector Node: Identified ${evidence.targetFiles.length} target files.`));
  } catch (err: any) {
    collectSpinner.fail(chalk.red(`Evidence Collector Node failed: ${err.message}`));
    state.errors.push(err.message);
    return state;
  }

  if (evidence.targetFiles.length === 0) {
    console.log(chalk.yellow('\nNo target files identified by Retrieval Agent. Stopping.'));
    return state;
  }

  // 3. Planner Node
  const planSpinner = ora(chalk.blue('Planner Node: Designing step-by-step resolution roadmap...')).start();
  let plan;
  try {
    plan = await runPlannerAgent(root, evidence, issue);
    planSpinner.succeed(chalk.green('Planner Node: Resolution blueprint created.'));
  } catch (err: any) {
    planSpinner.fail(chalk.red(`Planner Node failed: ${err.message}`));
    state.errors.push(err.message);
    return state;
  }

  console.log('\n' + chalk.bold.cyan('=== Planner Blueprint ==='));
  console.log(plan.explanation);
  console.log('Steps:');
  plan.planSteps.forEach((s, i) => console.log(`  ${i + 1}. ${s}`));
  console.log();

  if (plan.filesToModify.length === 0) {
    console.log(chalk.yellow('Planner identified no target files to modify. Stopping.'));
    return state;
  }

  // 4. Code Generation Node
  const codegenSpinner = ora(chalk.blue('Code Generation Node: Drafting code patches...')).start();
  let codegen;
  try {
    codegen = await runCodegenAgent(root, evidence, plan, issue);
    state.bugFix = {
      explanation: codegen.explanation,
      patches: codegen.patches,
      rawLLMResponse: '',
    };
    codegenSpinner.succeed(chalk.green('Code Generation Node: Patches generated.'));
  } catch (err: any) {
    codegenSpinner.fail(chalk.red(`Code Generation Node failed: ${err.message}`));
    state.errors.push(err.message);
    return state;
  }

  console.log('\n' + chalk.bold.cyan('=== Explanation of Changes ==='));
  console.log(codegen.explanation + '\n');

  if (codegen.patches.length === 0) {
    console.log(chalk.yellow('No search-replace blocks generated by Codegen Agent.'));
    return state;
  }

  // 5. Patch Validation Node
  const validation = validatePatches(root, codegen.patches);
  const successPatches = validation.results.filter(r => r.success);
  const failedPatches = validation.results.filter(r => !r.success);

  if (successPatches.length > 0) {
    console.log(chalk.bold.green('=== Preview of Changes ==='));
    for (const res of successPatches) {
      if (res.originalContent !== undefined && res.patchedContent !== undefined) {
        displayDiff(res.filePath, res.originalContent, res.patchedContent);
      }
    }
  }

  if (failedPatches.length > 0) {
    console.log(chalk.bold.red('=== Conflicting / Failed Matches ==='));
    for (const res of failedPatches) {
      console.log(`- File: ${chalk.cyan(res.filePath)}`);
      console.log(`  Error: ${chalk.red(res.error)}`);
    }
    console.log();
  }

  if (successPatches.length === 0) {
    console.log(chalk.red('All generated patches failed to align. Aborting.'));
    return state;
  }

  // 6. User Approval & Patch Application Agent Node
  let applyChanges = autoApply;
  if (!applyChanges) {
    const answer = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'confirmApply',
        message: 'Do you want to apply these changes to your project?',
        default: true,
      }
    ]);
    applyChanges = answer.confirmApply;
  }

  if (applyChanges) {
    const writeSpinner = ora(chalk.blue('Patch Application Node: Executing write updates...')).start();
    try {
      const finalResults = commitPatches(root, codegen.patches);
      const appliedPaths = finalResults.filter(r => r.success).map(r => r.filePath);
      writeSpinner.succeed(chalk.green(`Patch Application Node: Successfully wrote updates to ${appliedPaths.length} files.`));
      
      // Store in SQLite DB history
      await recordFixHistory(root, issue, appliedPaths);
    } catch (err: any) {
      writeSpinner.fail(chalk.red(`Patch Application Node failed to write: ${err.message}`));
      state.errors.push(err.message);
    }
  } else {
    console.log(chalk.yellow('\nChanges discarded.'));
  }

  return state;
}
